plugins { id 'com.android.application' }
android {
    namespace 'inc.cubitsystems.ontrac'
    compileSdk 34
    defaultConfig {
        applicationId "inc.cubitsystems.ontrac"
        minSdk 26
        targetSdk 34
        versionCode 14
        versionName "0.14.0"
    }
    buildTypes {
        release { minifyEnabled false }
        debug { versionNameSuffix "-debug" }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    packaging {
        resources {
            excludes += ['META-INF/DEPENDENCIES', 'META-INF/LICENSE', 'META-INF/LICENSE.txt', 'META-INF/license.txt', 'META-INF/NOTICE', 'META-INF/NOTICE.txt', 'META-INF/notice.txt', 'META-INF/*.kotlin_module']
        }
    }
}
dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
