plugins { id 'com.android.application' }
android {
    namespace 'inc.cubitsystems.ontrac'
    compileSdk 34
    defaultConfig {
        applicationId "inc.cubitsystems.ontrac"
        minSdk 26
        targetSdk 34
        versionCode 3
        versionName "0.3.0"
    }
    buildTypes {
        release { minifyEnabled false }
        debug { versionNameSuffix "-debug" }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.activity:activity:1.8.2'
    implementation 'androidx.core:core:1.12.0'
}
